spring:
  datasource:
    url: jdbc:postgresql://cloudtecnologia.dynns.com:5432/logistica
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 895674
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://cloudtecnologia.dynns.com:8180/realms/CLOUD_TECNOLOGIA
          client-id: maxima-logistica
          client-secret: 17DmswLn5mwQGsmbRqjxLA3c8U0c4lN0