spring:
  datasource:
    url: jdbc:postgresql://cloudtecnologia.dynns.com:5432/logistica
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 895674
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    hibernate:
      ddl-auto: update